language: go

go:
  - 1.12.x

go_import_path: github.com/Stackdriver/stackdriver-prometheus-sidecar

# This ensures that the local cache is filled before running the CI.
# travis_retry retries the command 3 times if it fails as we've experienced
# random issues on Travis.
before_install:
- travis_retry make deps

script:
- make test goveralls
- git diff --exit-code

# Contains tokens for Coveralls. See https://docs.coveralls.io/go
env:
  global:
    secure: sNu7aGQUNSMBDfwCjVQCOxNlpwD4tfQBP5owdYMQLs/vrLEEeKOIH/g8R2QdI2H9AVIFofpbEC6bR9VXP5eo1hTmwF3MgGS1e7zD61+wdE4fqDAau0AR3fP344yg/m0YjQVIj8fhPByd+6Sjgzlt9K8A4eQr7e3RbJc7qSKedU4L0N1VaJ/lOwnyBoL+UM1kgHopA+71EeEkpbp6C1NkavvEBZGNA8XZtQJWv8bWiFvbI38CPqIbNgXb+V5eSD2eqXoc2FFoX+JZsWibvE58ZgLjR4CrLkaS9zn7wMtbj0bzzrmTUKyXZBO90UMumQW9dehoDW4EoLI54qCgLeyIrKDh5vLfcgvjfWRKFAKwu3AARdFCNGNkkdjiA/n/JQ0mT/k5NGTwFKFupzQQuexQpqsAV/HPxI3wZCbMj2TX8wW49VPMrLrj6QmTgLS3xMNrHaeMYAdSlEIhoMMOm0XTIpdKJwUVLmHVClSWdVzAKWHnJIMPSgiRKn1g3fBYdlfY1au1Y5rGje/zH9Q6ljETyzNR9oIJCHXoDF59pTcsO7vXutnUTOO8INuGBcKijfj3mYnT5FDJm1kOtQM1RBSx9c5W6CbKWD7i5wVCcfH9BAO4ncmT2C+NmEXRotQvB//VgGL5TB6ZeMIYjWSnDbhpNOFsRwsc0UbIT3yOON26YAY=
